version: "3.8"

services:
  web:
    build: .
    container_name: python-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=12345qaz
      - DB_NAME=mydb
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345qaz
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
