# flask-deployment.yaml
# Создает Flask Pod с вашим Python приложением

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: stepproject4
spec:
  replicas: 2  # Один экземпляр Flask приложения
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        # ⚠️ ВАЖНО: Замените на ваш образ! 
        # Сначала соберите: docker build -t stepproject4-flask .
        # Затем тег для MiniKube: docker tag stepproject4-flask:latest stepproject4-flask:v1.0
        image: flask-mysql-app:2.0
        imagePullPolicy: Never  # Использовать локальный образ
        ports:
        - containerPort: 5000
        env:
        # Читаем все переменные из ConfigMap
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        # Проверка здоровья приложения
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10