apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword в base64
  mysql-password: YXBwcGFzc3dvcmQ=      # apppassword в base64
