#!/bin/bash

echo "enter namber"
read number
if [ $number -gt 1]; then 
	if [$number-lt 10 ]; then
	result=$((number*number))
	echo "the result is $result"

	
else
	 echo "the number is out of range"

	fi

else 
echo "2the nomber out of range"

fi

