version: '3.8'
services:
  web:
    image: nginx:latest
    restart: always    
    ports:
      -"80:80"
    depends_on:
      -db

  db:
    image: mysql:latest
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
