apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  labels:
    app: flask-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: flask-app