
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    app: flask-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/app
    type: DirectoryOrCreate

