- name: Install and configure nginx reverse proxy
  hosts: jenkins_master
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy nginx config
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: 0644

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
